apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
  project: default
  source:
    repoURL: https://github.com/cadugr/aula-gitops-argocd.git
    path: argocd 
    targetRevision: HEAD
    # directory:
    #   recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd